### ISSUE TITLE
Overflow in Safari

### ISSUE THREAD

**Issue by moebiusmania** [contactlab/contactlab-pattern-library#37]
Some Gist embeds results in overflowing the main wrapper horizontally on Safari (both iOS and MacOS)

![img_0001](https://cloud.githubusercontent.com/assets/1764542/21233194/908ae3da-c2ee-11e6-912d-cf5641395a6a.PNG)

**Comment by equinusocio** [comment]
Cant' reproduce this issue on MacOs Safari:
![screen shot 2017-07-24 at 10 44 24](https://user-images.githubusercontent.com/10454741/28515222-17738ba6-705d-11e7-81e8-a969a65ee6a2.png)
